### ISSUE TITLE
Exporter

### ISSUE THREAD

**Issue by josepowera** [aerospike/aerospike-loader#20]
This is importer from .DSV back into Aerospike...

Is there any exporter to export aerospike to DSV?  (something similar to https://github.com/aerospike-examples/csv-exporter) that would also create JSON for mapping (https://github.com/aerospike/aerospike-loader/blob/master/example/alldatatype.json) and .DSV format

**Comment by rbotzer** [comment]
Thanks for the suggestion, but the loader is a data importer, rather than an exporter, and will remain that way.

If you work on a .DSV exporter we can move your repo into aerospike-examples or aerospike-community.
