### ISSUE TITLE
How to set column_position/column_name when header_exist is false.

### ISSUE THREAD

**Issue by zhangnew** [aerospike/aerospike-loader#9]
I want use the first column as the key, but when I set this in the Configuration file:

```
            "key" : {
                "column_position" : 1,
                "type" : "string"
            },
```

run_loader then I get this error:

```
java.lang.Exception: Column position defined for data file without header !!
```

**Comment by kitex** [comment]
`if(dsvHasHeader()) { updateColumnInfoForMappingDefs(columnNames); }`

instead of `updateColumnInfoForMappingDefs(columnNames);`

It would work. 
I changed the code and checked it.

**Comment by arrowplum** [comment]
We have fixed this problem. A fix will be included in the next release.
